/* ============================================================
   SIGNAL — Daily letter-decryption movie guessing game
   Step 2 (game logic) — Added 2026-05-02

   Daily flow:
     1. OrbitUtils.getPuzzleIndex(SIGNAL_PUZZLES.length) → today's movie ID
     2. tmdbFetch /movie/{id} with credits → top 5 billed cast
     3. Player guesses letters (unlimited) → reveals across all 5 names
     4. Player identifies movie title (exact match, normalized)
     5. Win: rank by attempts via SCORE_TIERS; stats updated
     6. State persisted to orbit_signal_{Y}_{M}_{D} (M=getMonth, D=getDate)
   ============================================================ */

(function () {
  'use strict';

  // ============================================
  // CONSTANTS
  // ============================================

  // Daily puzzle list comes from games/signal-puzzles.js (window.SIGNAL_PUZZLES,
  // 364 IDs auto-generated by scripts/generate-signal-puzzles.py).
  // Inline list is a defensive fallback if the data file fails to load.
  var SIGNAL_PUZZLES = (typeof window !== 'undefined' && Array.isArray(window.SIGNAL_PUZZLES) && window.SIGNAL_PUZZLES.length)
    ? window.SIGNAL_PUZZLES
    : [27205, 603, 680, 13, 155]; // Inception, Matrix, Pulp Fiction, Forrest Gump, Dark Knight

  var SCORE_TIERS = [
    { max: 5,        label: 'Perfect signal',     color: 'var(--accent-gold)' },
    { max: 10,       label: 'Clear transmission', color: 'var(--accent-cyan)' },
    { max: 15,       label: 'Signal lock',        color: 'var(--prestige-purple)' },
    { max: 20,       label: 'Weak signal',        color: 'var(--muted-silver)' },
    { max: Infinity, label: 'Decoding…',     color: 'var(--ghost-gray)' }
  ];

  var HINT_COST = 3;          // Hint adds +3 to attempts
  var HINT_UNLOCK_AT = 5;     // Available once attempts >= 5
  var CAST_COUNT = 5;

  // ============================================
  // STATE
  // ============================================
  var state = null;       // Today's game state (see schema below)
  var stats = null;       // Persistent stats across days
  var dailyKey = '';      // localStorage key for today
  var STATS_KEY = 'orbit_signal_stats';

  /*
    state schema (persisted to dailyKey):
      movieId         number
      movieTitle      string
      actors          [{ id, name, photoPath, decoded, displayName }]
      revealedLetters string[]   (letters guessed; serialized array, not Set)
      attempts        number
      hintsUsed       number
      gameOver        bool
      won             bool
      rank            string     (current tier label)
      timestamp       number     (Date.now)

    stats schema (persisted to orbit_signal_stats):
      gamesPlayed, gamesWon, currentStreak, maxStreak,
      lastPlayedDate, totalAttempts, averageAttempts,
      distribution { '1-5','6-10','11-15','16-20','21+' }
  */

  // ============================================
  // DOM REFS
  // ============================================
  var $ = function (id) { return document.getElementById(id); };
  var letterGrid, attemptCount, rankBadge, actorFrames,
      movieInput, submitMovie, hintBtn, feedback;

  // ============================================
  // UTILS
  // ============================================

  /** Today's daily key: orbit_signal_{Y}_{M}_{D} (M=1-12 to match
      arcade.js getTodayKey + connections/journeys convention). */
  function buildDailyKey() {
    var d = new Date();
    return 'orbit_signal_' + d.getFullYear() + '_' + (d.getMonth() + 1) + '_' + d.getDate();
  }

  /** Strip diacritics so "Penélope" matches when player guesses E.
      ̀-ͯ covers the combining diacritical marks block. */
  function normalize(str) {
    return (str || '').normalize('NFD').replace(/[̀-ͯ]/g, '');
  }

  /** Letters only (A-Z). Spaces, hyphens, apostrophes, dots are revealed for free. */
  function isLetter(ch) {
    return /^[a-z]$/i.test(ch);
  }

  /** Build the masked display string for a name given currently revealed letters. */
  function maskName(name, revealed) {
    var normalized = normalize(name);
    var out = '';
    for (var i = 0; i < name.length; i++) {
      var raw = name[i];
      var norm = normalized[i];
      if (!isLetter(norm)) {
        out += raw; // space, hyphen, apostrophe, dot — always shown
      } else if (revealed.indexOf(norm.toLowerCase()) !== -1) {
        out += raw;
      } else {
        out += '_';
      }
    }
    return out;
  }

  /** Are all letters in the name revealed? */
  function isFullyDecoded(name, revealed) {
    var normalized = normalize(name).toLowerCase();
    for (var i = 0; i < normalized.length; i++) {
      var ch = normalized[i];
      if (isLetter(ch) && revealed.indexOf(ch) === -1) return false;
    }
    return true;
  }

  function tierForAttempts(attempts) {
    for (var i = 0; i < SCORE_TIERS.length; i++) {
      if (attempts <= SCORE_TIERS[i].max) return SCORE_TIERS[i];
    }
    return SCORE_TIERS[SCORE_TIERS.length - 1];
  }

  function bucketFor(attempts) {
    if (attempts <= 5) return '1-5';
    if (attempts <= 10) return '6-10';
    if (attempts <= 15) return '11-15';
    if (attempts <= 20) return '16-20';
    return '21+';
  }

  function showFeedback(message, kind) {
    feedback.textContent = message;
    feedback.classList.remove('success', 'error', 'hint');
    if (kind) feedback.classList.add(kind);
  }

  // ============================================
  // PERSISTENCE
  // ============================================

  function saveState() {
    if (!state) return;
    state.timestamp = Date.now();
    OrbitUtils.store.set(dailyKey, state);
  }

  function loadStats() {
    return OrbitUtils.store.get(STATS_KEY, {
      gamesPlayed: 0,
      gamesWon: 0,
      currentStreak: 0,
      maxStreak: 0,
      lastPlayedDate: null,
      totalAttempts: 0,
      averageAttempts: 0,
      distribution: { '1-5': 0, '6-10': 0, '11-15': 0, '16-20': 0, '21+': 0 }
    });
  }

  function recordWin(attempts) {
    var todayStr = new Date().toDateString();
    stats.gamesPlayed += 1;
    stats.gamesWon += 1;
    stats.totalAttempts += attempts;
    stats.averageAttempts = stats.totalAttempts / stats.gamesWon;
    stats.distribution[bucketFor(attempts)] += 1;

    // Streak: consecutive calendar-day wins. We compare yesterday's date string.
    var yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    if (stats.lastPlayedDate === yesterday.toDateString()) {
      stats.currentStreak += 1;
    } else if (stats.lastPlayedDate === todayStr) {
      // already counted today — leave streak as-is
    } else {
      stats.currentStreak = 1;
    }
    if (stats.currentStreak > stats.maxStreak) stats.maxStreak = stats.currentStreak;
    stats.lastPlayedDate = todayStr;

    OrbitUtils.store.set(STATS_KEY, stats);
  }

  // ============================================
  // FETCH PUZZLE
  // ============================================

  /**
   * Fetch movie details + top {CAST_COUNT} billed cast from TMDB.
   * Uses OrbitUtils.tmdbFetch (Rule #13).
   */
  function fetchPuzzle(movieId) {
    return OrbitUtils.tmdbFetch('/movie/' + movieId, { append_to_response: 'credits' })
      .then(function (data) {
        var cast = (data.credits && data.credits.cast) || [];
        var top = cast.slice(0, CAST_COUNT).map(function (c) {
          return {
            id: c.id,
            name: c.name,
            photoPath: c.profile_path,
            decoded: false,
            displayName: '' // populated by render via maskName
          };
        });
        return { movieId: data.id, movieTitle: data.title, actors: top };
      });
  }

  // ============================================
  // RENDERING
  // ============================================

  function buildLetterGrid() {
    letterGrid.innerHTML = '';
    for (var i = 0; i < 26; i++) {
      var letter = String.fromCharCode(65 + i); // A-Z
      var btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'letter-btn';
      btn.textContent = letter;
      btn.dataset.letter = letter.toLowerCase();
      btn.addEventListener('click', onLetterClick);
      letterGrid.appendChild(btn);
    }
  }

  function renderActors() {
    actorFrames.innerHTML = '';
    state.actors.forEach(function (actor) {
      var frame = document.createElement('div');
      frame.className = 'actor-frame' + (actor.decoded ? ' decoded' : '');

      var portrait = document.createElement('div');
      portrait.className = 'actor-portrait';

      var img = document.createElement('img');
      img.className = 'actor-img';
      img.alt = actor.decoded ? actor.name : 'Encrypted actor';
      var imgUrl = OrbitUtils.tmdbImageUrl(actor.photoPath, OrbitUtils.IMAGE_SIZES.PROFILE_MD);
      if (imgUrl) img.src = imgUrl;
      portrait.appendChild(img);

      var scan = document.createElement('div');
      scan.className = 'scanline-overlay';
      portrait.appendChild(scan);

      frame.appendChild(portrait);

      var nameEl = document.createElement('div');
      nameEl.className = 'actor-name' + (actor.decoded ? '' : ' encrypted');
      nameEl.textContent = actor.decoded
        ? actor.name
        : maskName(actor.name, state.revealedLetters);
      frame.appendChild(nameEl);

      actorFrames.appendChild(frame);
    });
  }

  function syncLetterButtons() {
    var btns = letterGrid.querySelectorAll('.letter-btn');
    for (var i = 0; i < btns.length; i++) {
      var letter = btns[i].dataset.letter;
      if (state.revealedLetters.indexOf(letter) !== -1) {
        btns[i].classList.add('used');
        btns[i].disabled = true;
      } else {
        btns[i].classList.remove('used');
        btns[i].disabled = false;
      }
    }
  }

  function updateScorePanel() {
    attemptCount.textContent = state.attempts;
    var tier = tierForAttempts(state.attempts);
    state.rank = tier.label;
    rankBadge.textContent = tier.label;
    rankBadge.style.color = tier.color;
  }

  function updateHintButton() {
    var unlocked = state.attempts >= HINT_UNLOCK_AT && !state.gameOver;
    if (unlocked) {
      hintBtn.classList.remove('locked');
      hintBtn.setAttribute('aria-disabled', 'false');
      hintBtn.innerHTML =
        '<span class="og og-lightbulb" aria-hidden="true"></span>' +
        '<span class="hint-label">HINT &mdash; Reveal first letter (+' + HINT_COST + ')</span>';
    } else {
      hintBtn.classList.add('locked');
      hintBtn.setAttribute('aria-disabled', 'true');
      var remaining = Math.max(0, HINT_UNLOCK_AT - state.attempts);
      hintBtn.innerHTML =
        '<span class="og og-lock" aria-hidden="true"></span>' +
        '<span class="hint-label">HINT &mdash; ' + remaining + ' more to unlock</span>';
    }
  }

  function lockBoardForGameOver() {
    var btns = letterGrid.querySelectorAll('.letter-btn');
    for (var i = 0; i < btns.length; i++) {
      btns[i].disabled = true;
      btns[i].classList.add('used');
    }
    movieInput.disabled = true;
    submitMovie.disabled = true;
    hintBtn.classList.add('locked');
    hintBtn.setAttribute('aria-disabled', 'true');
  }

  function renderAll() {
    syncLetterButtons();
    renderActors();
    updateScorePanel();
    updateHintButton();
    if (state.gameOver) lockBoardForGameOver();
  }

  // ============================================
  // GAME ACTIONS
  // ============================================

  function onLetterClick(e) {
    if (state.gameOver) return;
    var letter = e.currentTarget.dataset.letter;
    guessLetter(letter);
  }

  function guessLetter(letter) {
    letter = letter.toLowerCase();
    if (!isLetter(letter)) return;
    if (state.revealedLetters.indexOf(letter) !== -1) return;

    state.revealedLetters.push(letter);
    state.attempts += 1;

    var anyMatch = false;
    state.actors.forEach(function (actor) {
      if (normalize(actor.name).toLowerCase().indexOf(letter) !== -1) anyMatch = true;
      if (!actor.decoded && isFullyDecoded(actor.name, state.revealedLetters)) {
        actor.decoded = true;
      }
    });

    showFeedback(
      anyMatch
        ? '✓ Letter "' + letter.toUpperCase() + '" found in the signal'
        : '× No "' + letter.toUpperCase() + '" detected',
      anyMatch ? 'success' : 'error'
    );

    renderAll();
    saveState();
  }

  function guessMovie() {
    if (state.gameOver) return;
    var raw = movieInput.value;
    if (!raw || !raw.trim()) {
      showFeedback('Enter a movie title to identify the signal', 'error');
      return;
    }
    state.attempts += 1;

    var guess = normalize(raw.trim().toLowerCase());
    var solution = normalize(state.movieTitle.toLowerCase());

    if (guess === solution) {
      win();
    } else {
      showFeedback('× Not "' + raw.trim() + '" — keep decoding', 'error');
      movieInput.value = '';
      renderAll();
      saveState();
    }
  }

  function win() {
    state.gameOver = true;
    state.won = true;
    state.actors.forEach(function (a) { a.decoded = true; });
    var tier = tierForAttempts(state.attempts);
    state.rank = tier.label;

    recordWin(state.attempts);
    saveState();

    showFeedback(
      '★ ' + state.movieTitle + ' — ' + tier.label + ' (' + state.attempts + ' attempts)',
      'success'
    );
    renderAll();
  }

  function useHint() {
    if (state.gameOver) return;
    if (state.attempts < HINT_UNLOCK_AT) return;

    var target = null;
    for (var i = 0; i < state.actors.length; i++) {
      if (!state.actors[i].decoded) { target = state.actors[i]; break; }
    }
    if (!target) return; // all decoded already

    // First letter of the actor's name (skip any non-letter prefix, defensive)
    var normalized = normalize(target.name);
    var firstLetter = '';
    for (var j = 0; j < normalized.length; j++) {
      if (isLetter(normalized[j])) { firstLetter = normalized[j].toLowerCase(); break; }
    }
    if (!firstLetter) return;

    state.hintsUsed += 1;
    state.attempts += HINT_COST - 1; // guessLetter adds +1, hint costs +3 total

    if (state.revealedLetters.indexOf(firstLetter) === -1) {
      // guessLetter handles increment (+1), reveal, render, save
      guessLetter(firstLetter);
    } else {
      // Already revealed — still charge cost but don't double-reveal
      state.attempts += 1;
      renderAll();
      saveState();
    }

    showFeedback(
      '○ Hint used — first letter "' + firstLetter.toUpperCase() + '" revealed (+' + HINT_COST + ' attempts)',
      'hint'
    );
  }

  // ============================================
  // INIT
  // ============================================

  function attachDOMRefs() {
    letterGrid   = $('letterGrid');
    attemptCount = $('attemptCount');
    rankBadge    = $('rankBadge');
    actorFrames  = $('actorFrames');
    movieInput   = $('movieInput');
    submitMovie  = $('submitMovie');
    hintBtn      = $('hintBtn');
    feedback     = $('feedback');
  }

  function attachListeners() {
    submitMovie.addEventListener('click', guessMovie);
    movieInput.addEventListener('keydown', function (e) {
      if (e.key === 'Enter') { e.preventDefault(); guessMovie(); }
    });
    hintBtn.addEventListener('click', useHint);

    document.addEventListener('keydown', function (e) {
      if (state == null || state.gameOver) return;
      if (document.activeElement === movieInput) return; // typing in input
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      var k = (e.key || '').toLowerCase();
      if (k.length === 1 && isLetter(k)) {
        guessLetter(k);
      }
    });
  }

  function init() {
    attachDOMRefs();
    buildLetterGrid();
    attachListeners();
    stats = loadStats();
    dailyKey = buildDailyKey();

    var existing = OrbitUtils.store.get(dailyKey, null);
    if (existing && existing.movieId && existing.actors && existing.actors.length) {
      state = existing;
      // Backfill defensive fields if older state shape
      if (!Array.isArray(state.revealedLetters)) state.revealedLetters = [];
      if (typeof state.hintsUsed !== 'number') state.hintsUsed = 0;
      renderAll();
      if (state.gameOver && state.won) {
        showFeedback(
          '★ ' + state.movieTitle + ' — ' + state.rank + ' (' + state.attempts + ' attempts)',
          'success'
        );
      } else {
        showFeedback('Resuming today’s signal…', null);
      }
      return;
    }

    var idx = OrbitUtils.getPuzzleIndex(SIGNAL_PUZZLES.length);
    var movieId = SIGNAL_PUZZLES[idx];

    showFeedback('Loading today’s transmission…', null);
    fetchPuzzle(movieId).then(function (puzzle) {
      state = {
        movieId: puzzle.movieId,
        movieTitle: puzzle.movieTitle,
        actors: puzzle.actors,
        revealedLetters: [],
        attempts: 0,
        hintsUsed: 0,
        gameOver: false,
        won: false,
        rank: SCORE_TIERS[0].label,
        timestamp: Date.now()
      };
      saveState();
      renderAll();
      showFeedback('Click letters to decode the signal…', null);
    }).catch(function (err) {
      console.error('[signal] failed to load puzzle', err);
      showFeedback('Signal lost — unable to load today’s transmission', 'error');
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
