/*
 * STRATA — daily boards
 * Verified quota-4 generations (four single-tiles per card) with a soft 3×4 opener:
 * generation 0 fills layer 1, so the board opens on a single card row and further
 * decks surface as you dig. Every keystone is buried under one of its own singles.
 * Collision-free by construction; all boards solvable by perfect play.
 *
 * This static set is the port seed. The live daily engine (TMDB popularity pool +
 * date seed + real poster art) will later replace this file's contents only.
 *
 * Board shape:
 *   { gens: [ { cards:[{axis,label} x3], keystone:"<film>" } x3 ],
 *     stacks: [ [ {t:"<film>", g:<genIndex>, a:"DECADE|DIRECTOR|ACTOR|K"} ... ] x9 ] }
 */
const STRATA_BOARDS = [
  // Daily 184 — keystones: Last Vegas, The Untouchables, Meet the Fockers
  {"gens":[{"cards":[{"axis":"DECADE","label":"2010"},{"axis":"DIRECTOR","label":"Jon Turteltaub"},{"axis":"ACTOR","label":"Michael Douglas"}],"keystone":"Last Vegas"},{"cards":[{"axis":"DECADE","label":"1980"},{"axis":"DIRECTOR","label":"Brian De Palma"},{"axis":"ACTOR","label":"Sean Connery"}],"keystone":"The Untouchables"},{"cards":[{"axis":"DECADE","label":"2000"},{"axis":"DIRECTOR","label":"Jay Roach"},{"axis":"ACTOR","label":"Ben Stiller"}],"keystone":"Meet the Fockers"}],"stacks":[[{"t":"Red","g":0,"a":"DECADE"},{"t":"Instinct","g":0,"a":"DIRECTOR"},{"t":"Lonesome Dove","g":1,"a":"DECADE"},{"t":"Little Fockers","g":2,"a":"ACTOR"},{"t":"Bombshell","g":2,"a":"DIRECTOR"}],[{"t":"Traffic","g":0,"a":"ACTOR"},{"t":"While You Were Sleeping","g":0,"a":"DIRECTOR"},{"t":"The Rock","g":1,"a":"ACTOR"},{"t":"The Good Shepherd","g":2,"a":"DECADE"},{"t":"Dinner for Schmucks","g":2,"a":"DIRECTOR"}],[{"t":"Grudge Match","g":0,"a":"DECADE"},{"t":"Disclosure","g":0,"a":"ACTOR"},{"t":"The Mission","g":1,"a":"DECADE"},{"t":"Zoolander 2","g":2,"a":"ACTOR"},{"t":"Meet the Fockers","g":2,"a":"K"}],[{"t":"Falling Down","g":0,"a":"ACTOR"},{"t":"Last Vegas","g":0,"a":"K"},{"t":"The Hunt for Red October","g":1,"a":"ACTOR"},{"t":"The Hours","g":2,"a":"DECADE"}],[{"t":"The Family","g":0,"a":"DECADE"},{"t":"Carlito's Way","g":1,"a":"DIRECTOR"},{"t":"Falling in Love","g":1,"a":"DECADE"},{"t":"Reality Bites","g":2,"a":"ACTOR"}],[{"t":"The American President","g":0,"a":"ACTOR"},{"t":"Mission: Impossible","g":1,"a":"DIRECTOR"},{"t":"The Anderson Tapes","g":1,"a":"ACTOR"},{"t":"What Just Happened","g":2,"a":"DECADE"}],[{"t":"RED 2","g":0,"a":"DECADE"},{"t":"Hi, Mom!","g":1,"a":"DIRECTOR"},{"t":"The Right Stuff","g":1,"a":"DECADE"},{"t":"Night at the Museum: Secret of the Tomb","g":2,"a":"ACTOR"}],[{"t":"National Treasure: Book of Secrets","g":0,"a":"DIRECTOR"},{"t":"Obsession","g":1,"a":"DIRECTOR"},{"t":"The Untouchables","g":1,"a":"K"},{"t":"Space Cowboys","g":2,"a":"DECADE"}],[{"t":"Phenomenon","g":0,"a":"DIRECTOR"},{"t":"A Bridge Too Far","g":1,"a":"ACTOR"},{"t":"Mystery, Alaska","g":2,"a":"DIRECTOR"},{"t":"Game Change","g":2,"a":"DIRECTOR"}]]},
  // Daily 185 — keystones: The Untouchables, Last Vegas, The Godfather Part II
  {"gens":[{"cards":[{"axis":"DECADE","label":"1980"},{"axis":"DIRECTOR","label":"Brian De Palma"},{"axis":"ACTOR","label":"Sean Connery"}],"keystone":"The Untouchables"},{"cards":[{"axis":"DECADE","label":"2010"},{"axis":"DIRECTOR","label":"Jon Turteltaub"},{"axis":"ACTOR","label":"Michael Douglas"}],"keystone":"Last Vegas"},{"cards":[{"axis":"DECADE","label":"1970"},{"axis":"DIRECTOR","label":"Francis Ford Coppola"},{"axis":"ACTOR","label":"Al Pacino"}],"keystone":"The Godfather Part II"}],"stacks":[[{"t":"Falling in Love","g":0,"a":"DECADE"},{"t":"The Black Dahlia","g":0,"a":"DIRECTOR"},{"t":"Red","g":1,"a":"DECADE"},{"t":"Heat","g":2,"a":"ACTOR"},{"t":"Jack","g":2,"a":"DIRECTOR"}],[{"t":"A Bridge Too Far","g":0,"a":"ACTOR"},{"t":"Hi, Mom!","g":0,"a":"DIRECTOR"},{"t":"Traffic","g":1,"a":"ACTOR"},{"t":"The Deer Hunter","g":2,"a":"DECADE"},{"t":"The Rainmaker","g":2,"a":"DIRECTOR"}],[{"t":"Lonesome Dove","g":0,"a":"DECADE"},{"t":"The Rock","g":0,"a":"ACTOR"},{"t":"Little Fockers","g":1,"a":"DECADE"},{"t":"Glengarry Glen Ross","g":2,"a":"ACTOR"},{"t":"The Godfather Part II","g":2,"a":"K"}],[{"t":"The Anderson Tapes","g":0,"a":"ACTOR"},{"t":"The Untouchables","g":0,"a":"K"},{"t":"Falling Down","g":1,"a":"ACTOR"},{"t":"Taxi Driver","g":2,"a":"DECADE"}],[{"t":"The Mission","g":0,"a":"DECADE"},{"t":"National Treasure: Book of Secrets","g":1,"a":"DIRECTOR"},{"t":"Grudge Match","g":1,"a":"DECADE"},{"t":"Any Given Sunday","g":2,"a":"ACTOR"}],[{"t":"Rising Sun","g":0,"a":"ACTOR"},{"t":"Phenomenon","g":1,"a":"DIRECTOR"},{"t":"Disclosure","g":1,"a":"ACTOR"},{"t":"Cisco Pike","g":2,"a":"DECADE"}],[{"t":"True Confessions","g":0,"a":"DECADE"},{"t":"Instinct","g":1,"a":"DIRECTOR"},{"t":"The Monuments Men","g":1,"a":"DECADE"},{"t":"City Hall","g":2,"a":"ACTOR"}],[{"t":"Carlito's Way","g":0,"a":"DIRECTOR"},{"t":"While You Were Sleeping","g":1,"a":"DIRECTOR"},{"t":"Last Vegas","g":1,"a":"K"},{"t":"Lucky Lady","g":2,"a":"DECADE"}],[{"t":"Mission: Impossible","g":0,"a":"DIRECTOR"},{"t":"You, Me and Dupree","g":1,"a":"ACTOR"},{"t":"Peggy Sue Got Married","g":2,"a":"DIRECTOR"},{"t":"Gardens of Stone","g":2,"a":"DIRECTOR"}]]},
  // Daily 186 — keystones: The Untouchables, Last Vegas, The Godfather
  {"gens":[{"cards":[{"axis":"DECADE","label":"1980"},{"axis":"DIRECTOR","label":"Brian De Palma"},{"axis":"ACTOR","label":"Sean Connery"}],"keystone":"The Untouchables"},{"cards":[{"axis":"DECADE","label":"2010"},{"axis":"DIRECTOR","label":"Jon Turteltaub"},{"axis":"ACTOR","label":"Michael Douglas"}],"keystone":"Last Vegas"},{"cards":[{"axis":"DECADE","label":"1970"},{"axis":"DIRECTOR","label":"Francis Ford Coppola"},{"axis":"ACTOR","label":"Marlon Brando"}],"keystone":"The Godfather"}],"stacks":[[{"t":"Lonesome Dove","g":0,"a":"DECADE"},{"t":"The Black Dahlia","g":0,"a":"DIRECTOR"},{"t":"Grudge Match","g":1,"a":"DECADE"},{"t":"The Score","g":2,"a":"ACTOR"},{"t":"Tucker: The Man and His Dream","g":2,"a":"DIRECTOR"}],[{"t":"The Anderson Tapes","g":0,"a":"ACTOR"},{"t":"Mission to Mars","g":0,"a":"DIRECTOR"},{"t":"Falling Down","g":1,"a":"ACTOR"},{"t":"The Deer Hunter","g":2,"a":"DECADE"},{"t":"Peggy Sue Got Married","g":2,"a":"DIRECTOR"}],[{"t":"Falling in Love","g":0,"a":"DECADE"},{"t":"A Bridge Too Far","g":0,"a":"ACTOR"},{"t":"Red","g":1,"a":"DECADE"},{"t":"A Dry White Season","g":2,"a":"ACTOR"},{"t":"The Godfather","g":2,"a":"K"}],[{"t":"Rising Sun","g":0,"a":"ACTOR"},{"t":"The Untouchables","g":0,"a":"K"},{"t":"You, Me and Dupree","g":1,"a":"ACTOR"},{"t":"Taxi Driver","g":2,"a":"DECADE"}],[{"t":"True Confessions","g":0,"a":"DECADE"},{"t":"National Treasure: Book of Secrets","g":1,"a":"DIRECTOR"},{"t":"Little Fockers","g":1,"a":"DECADE"},{"t":"The Freshman","g":2,"a":"ACTOR"}],[{"t":"The Rock","g":0,"a":"ACTOR"},{"t":"Phenomenon","g":1,"a":"DIRECTOR"},{"t":"Disclosure","g":1,"a":"ACTOR"},{"t":"Lucky Lady","g":2,"a":"DECADE"}],[{"t":"The Mission","g":0,"a":"DECADE"},{"t":"Instinct","g":1,"a":"DIRECTOR"},{"t":"You Don't Know Jack","g":1,"a":"DECADE"},{"t":"Don Juan DeMarco","g":2,"a":"ACTOR"}],[{"t":"Carlito's Way","g":0,"a":"DIRECTOR"},{"t":"The Kid","g":1,"a":"DIRECTOR"},{"t":"Last Vegas","g":1,"a":"K"},{"t":"Thunderbolt and Lightfoot","g":2,"a":"DECADE"}],[{"t":"Mission: Impossible","g":0,"a":"DIRECTOR"},{"t":"Traffic","g":1,"a":"ACTOR"},{"t":"Jack","g":2,"a":"DIRECTOR"},{"t":"The Rainmaker","g":2,"a":"DIRECTOR"}]]},
  // Daily 187 — keystones: Last Vegas, The Godfather Part II, Meet the Fockers
  {"gens":[{"cards":[{"axis":"DECADE","label":"2010"},{"axis":"DIRECTOR","label":"Jon Turteltaub"},{"axis":"ACTOR","label":"Michael Douglas"}],"keystone":"Last Vegas"},{"cards":[{"axis":"DECADE","label":"1970"},{"axis":"DIRECTOR","label":"Francis Ford Coppola"},{"axis":"ACTOR","label":"Al Pacino"}],"keystone":"The Godfather Part II"},{"cards":[{"axis":"DECADE","label":"2000"},{"axis":"DIRECTOR","label":"Jay Roach"},{"axis":"ACTOR","label":"Ben Stiller"}],"keystone":"Meet the Fockers"}],"stacks":[[{"t":"Grudge Match","g":0,"a":"DECADE"},{"t":"Instinct","g":0,"a":"DIRECTOR"},{"t":"The Deer Hunter","g":1,"a":"DECADE"},{"t":"Night at the Museum: Secret of the Tomb","g":2,"a":"ACTOR"},{"t":"Bombshell","g":2,"a":"DIRECTOR"}],[{"t":"The American President","g":0,"a":"ACTOR"},{"t":"While You Were Sleeping","g":0,"a":"DIRECTOR"},{"t":"Any Given Sunday","g":1,"a":"ACTOR"},{"t":"The Good Shepherd","g":2,"a":"DECADE"},{"t":"Dinner for Schmucks","g":2,"a":"DIRECTOR"}],[{"t":"Little Fockers","g":0,"a":"DECADE"},{"t":"Wall Street","g":0,"a":"ACTOR"},{"t":"Taxi Driver","g":1,"a":"DECADE"},{"t":"There's Something About Mary","g":2,"a":"ACTOR"},{"t":"Meet the Fockers","g":2,"a":"K"}],[{"t":"Traffic","g":0,"a":"ACTOR"},{"t":"Last Vegas","g":0,"a":"K"},{"t":"Looking for Richard","g":1,"a":"ACTOR"},{"t":"The Hours","g":2,"a":"DECADE"}],[{"t":"The Family","g":0,"a":"DECADE"},{"t":"The Rainmaker","g":1,"a":"DIRECTOR"},{"t":"Cisco Pike","g":1,"a":"DECADE"},{"t":"The Secret Life of Walter Mitty","g":2,"a":"ACTOR"}],[{"t":"Disclosure","g":0,"a":"ACTOR"},{"t":"Rumble Fish","g":1,"a":"DIRECTOR"},{"t":"Carlito's Way","g":1,"a":"ACTOR"},{"t":"What Just Happened","g":2,"a":"DECADE"}],[{"t":"Glass","g":0,"a":"DECADE"},{"t":"Gardens of Stone","g":1,"a":"DIRECTOR"},{"t":"Night Moves","g":1,"a":"DECADE"},{"t":"Zoolander 2","g":2,"a":"ACTOR"}],[{"t":"National Treasure: Book of Secrets","g":0,"a":"DIRECTOR"},{"t":"Peggy Sue Got Married","g":1,"a":"DIRECTOR"},{"t":"The Godfather Part II","g":1,"a":"K"},{"t":"Space Cowboys","g":2,"a":"DECADE"}],[{"t":"Phenomenon","g":0,"a":"DIRECTOR"},{"t":"Heat","g":1,"a":"ACTOR"},{"t":"Mystery, Alaska","g":2,"a":"DIRECTOR"},{"t":"Game Change","g":2,"a":"DIRECTOR"}]]},
  // Daily 188 — keystones: The Deer Hunter, National Treasure: Book of Secrets, Power
  {"gens":[{"cards":[{"axis":"DECADE","label":"1970"},{"axis":"DIRECTOR","label":"Michael Cimino"},{"axis":"ACTOR","label":"Robert De Niro"}],"keystone":"The Deer Hunter"},{"cards":[{"axis":"DECADE","label":"2000"},{"axis":"DIRECTOR","label":"Jon Turteltaub"},{"axis":"ACTOR","label":"Nicolas Cage"}],"keystone":"National Treasure: Book of Secrets"},{"cards":[{"axis":"DECADE","label":"1980"},{"axis":"DIRECTOR","label":"Sidney Lumet"},{"axis":"ACTOR","label":"Richard Gere"}],"keystone":"Power"}],"stacks":[[{"t":"Deliverance","g":0,"a":"DECADE"},{"t":"The Sunchaser","g":0,"a":"DIRECTOR"},{"t":"Runaway Jury","g":1,"a":"DECADE"},{"t":"The Jackal","g":2,"a":"ACTOR"},{"t":"Q&A","g":2,"a":"DIRECTOR"}],[{"t":"Falling in Love","g":0,"a":"ACTOR"},{"t":"Year of the Dragon","g":0,"a":"DIRECTOR"},{"t":"Kiss of Death","g":1,"a":"ACTOR"},{"t":"The Mission","g":2,"a":"DECADE"},{"t":"Gloria","g":2,"a":"DIRECTOR"}],[{"t":"Manhattan","g":0,"a":"DECADE"},{"t":"Cop Land","g":0,"a":"ACTOR"},{"t":"The Men Who Stare at Goats","g":1,"a":"DECADE"},{"t":"Final Analysis","g":2,"a":"ACTOR"},{"t":"Power","g":2,"a":"K"}],[{"t":"Grudge Match","g":0,"a":"ACTOR"},{"t":"The Deer Hunter","g":0,"a":"K"},{"t":"The Rock","g":1,"a":"ACTOR"},{"t":"Lonesome Dove","g":2,"a":"DECADE"}],[{"t":"The Godfather","g":0,"a":"DECADE"},{"t":"Phenomenon","g":1,"a":"DIRECTOR"},{"t":"The Hours","g":1,"a":"DECADE"},{"t":"Sommersby","g":2,"a":"ACTOR"}],[{"t":"Jackie Brown","g":0,"a":"ACTOR"},{"t":"Instinct","g":1,"a":"DIRECTOR"},{"t":"Wild at Heart","g":1,"a":"ACTOR"},{"t":"True Confessions","g":2,"a":"DECADE"}],[{"t":"Lucky Lady","g":0,"a":"DECADE"},{"t":"While You Were Sleeping","g":1,"a":"DIRECTOR"},{"t":"Space Cowboys","g":1,"a":"DECADE"},{"t":"Brooklyn's Finest","g":2,"a":"ACTOR"}],[{"t":"Heaven's Gate","g":0,"a":"DIRECTOR"},{"t":"The Meg","g":1,"a":"DIRECTOR"},{"t":"National Treasure: Book of Secrets","g":1,"a":"K"},{"t":"Under Fire","g":2,"a":"DECADE"}],[{"t":"Desperate Hours","g":0,"a":"DIRECTOR"},{"t":"Con Air","g":1,"a":"ACTOR"},{"t":"Dog Day Afternoon","g":2,"a":"DIRECTOR"},{"t":"The Anderson Tapes","g":2,"a":"DIRECTOR"}]]}
];

if (typeof window !== 'undefined') window.STRATA_BOARDS = STRATA_BOARDS;
