[build]
  publish = "."
  command = "node scripts/generate-config.mjs"
  functions = "netlify/functions"

[[redirects]]
  from = "/config.js"
  to = "/runtime-config.js"
  status = 200

[[redirects]]
  from = "/api/tmdb"
  to = "/.netlify/functions/tmdb"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
